### ISSUE TITLE
get_defined_chars function seems to not work for some ttf files

### ISSUE THREAD

**Issue by YIYANGCAI** [clovaai/mxfont#10]
Hello, thanks for the this amazing work in few-shot font generation!

When I want to train the model on my own ttf files, I met a problem. When I tried to utilize the **get_chars_from_ttf.py**, some of my ttf files can only produces the alphabets some punctuations, and no chinese chars is produced. However, the ttfs does have included chinese chars. I am not sure if there is some limitation of fontTools when it read in the ttf files. Could you help me to explain the reasons? Thanks for your help!

![8281635197302_ pic](https://user-images.githubusercontent.com/49231152/138773678-cf6eb05a-2324-45b2-b70d-1d78e627cd40.jpg)

![8291635197328_ pic](https://user-images.githubusercontent.com/49231152/138773701-2b6db163-78d7-4f91-8aa2-a4233040a6d1.jpg)

**Comment by YIYANGCAI** [comment]
Anyway, I have found out that when I change the index of 0 in ttf["camp"].tables[0].camp.keys() to 1, which refers to 
```python3
chrs = [chr(y) for y in ttf["cmap"].tables[1].cmap.keys()] 
```
the terminal seems to output a lots of wanted chars. 
Therefore, I think a modification can be as the following:
changing the second line in get_defined_chars() function to:
```python
chars = chain.from_iterable([y + (Unicode[y[0]],) for y in x.cmap.items()] for x in ttf["cmap"].tables)
```

**Comment by 8uos** [comment]
Hi, thanks for the suggestion.
I am so sorry, but I cannot explain the reason clearly because I am also unfamiliar with the fontTools...
I have checked the code for my font files, but it seems there are some exceptions.
Did you succeed to get the available Chinese characters from your font file?
If then, I will update the code.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
