### ISSUE TITLE
while eval, get_defined_chars function can not get any Chinese character data! There is no output.

### ISSUE THREAD

**Issue by sAuDoisy** [clovaai/mxfont#13]
I gave the font file I downloaded myself, the font is correct and can be installed, but while testing, I found that there is no output pictures, I found that when using “get_defined_chars(fontfile)” function, there are only symbols like “！@#￥%…&×（）” in "chars". So the gen_chars and data_list is empty! I'm so sorry, but why

**Comment by Matt-JyS** [comment]
I met same issue regarding obtaining available characters for some fonts. Have you solved it? Thanks very much.

**Comment by Matt-JyS** [comment]
> I gave the font file I downloaded myself, the font is correct and can be installed, but while testing, I found that there is no output pictures, I found that when using “get_defined_chars(fontfile)” function, there are only symbols like “！@#￥%…&×（）” in "chars". So the gen_chars and data_list is empty! I'm so sorry, but why

i met same issue, have you resolved it? Thanks!

**Comment by SanghyukChun** [comment]
Hi, there is already a relevant issue, and we also do not have a solution for this.
https://github.com/clovaai/mxfont/issues/10

This is an issue with the fontTools, so please check the official document of fontTools.
https://fonttools.readthedocs.io/en/latest/ttLib/index.html

**Comment by Matt-JyS** [comment]
> 

Thanks for your reply. I will search it up. Kindly.
