### ISSUE TITLE
Thank you for your excellent work. I want to know how to generate a complete set of TTF format files of fonts?

### ISSUE THREAD

**Issue by MtYCNN** [clovaai/mxfont#15]
Currently, a group of images are generated. Should TTF font files not be directly output?

**Comment by SanghyukChun** [comment]
There are many ways to make a complete font set from images.
I recommend [FontForge](https://fontforge.org/en-US/) to deploy your own font.

Please check the following link for details
https://stackoverflow.com/questions/63380545/how-to-convert-a-set-of-images-into-a-font-ttf-file-with-python

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
