### ISSUE TITLE
There are some smudge in the infer result  image

### ISSUE THREAD

**Issue by ghost** [clovaai/mxfont#16]
This is an interesting work.But i got some issue when i try inference with the weight you provide . There are some dark line in the result image. 
![明](https://user-images.githubusercontent.com/20164277/202639797-21c04610-06fc-4605-9292-6808d2797223.png)
and this is my refer style image
![并](https://user-images.githubusercontent.com/20164277/202639874-aa95e604-d7a4-4e77-b6cd-9ffc0b4eb7fc.png)

**Comment by ghost** [comment]
it seem's that there are some bug in inference.ipynb. I got the clean result with the eval.py

**Comment by SanghyukChun** [comment]
Thanks. It seems that the issue is already resolved.
Please re-open the issue as necessary.

**Comment by Matt-JyS** [comment]
> it seem's that there are some bug in inference.ipynb. I got the clean result with the eval.py

Hi, May I ask for your help? i got nothing using eval.py. I have finished training and saved this pth file, but running eval.py gives nothing. No error was reported. But the test result folder contains nothing. why is that? Thanks very much.
