### ISSUE TITLE
Why do the models I trained predict the same results in two folders

### ISSUE THREAD

**Issue by zhenzi0322** [clovaai/mxfont#19]
I am using the original training method of mxfont, and the dataset is also included with mxfont

![Snipaste_2023-07-07_09-45-42](https://github.com/clovaai/mxfont/assets/34839719/b8cac269-a9ba-4f48-88fc-03fca635bd96)

**Comment by 8uos** [comment]
Hi, we do not provide the training dataset. 
The uploaded ttf files are solely intended for reference purposes to understand the structure of the dataset.
Kindly review the training settings and provide a detailed description of them.

**Comment by SanghyukChun** [comment]
Closing the issue as assuming that our comment resolved the issue.
