### ISSUE TITLE
There is a problem with the predicted character image

### ISSUE THREAD

**Issue by zhenzi0322** [clovaai/mxfont#20]
I found that the character image is abnormal when I used the conference.ipynb file for prediction

![Snipaste_2023-07-07_10-02-51](https://github.com/clovaai/mxfont/assets/34839719/06c2dcb4-6eff-4ccc-9f3e-5d822dc7555a)

**Comment by 8uos** [comment]
We offer a straightforward refining function to eliminate the artifacts. Please refer to this code ([source](https://github.com/clovaai/mxfont/blob/fa3721e9a2fa9effee15431d86a4221cde4cabe4/utils/visualize.py#L12)) for implementation details.

You can utilize it as shown below ([usage](https://github.com/clovaai/mxfont/blob/fa3721e9a2fa9effee15431d86a4221cde4cabe4/eval.py#L50C1-L51C1)).

**Comment by zhenzi0322** [comment]
It's not a artifact, but the word doesn't exist

**Comment by SanghyukChun** [comment]
Closing the issue with the same reason of #24
