### ISSUE TITLE
Got nothing after test using eval.py

### ISSUE THREAD

**Issue by Matt-JyS** [clovaai/mxfont#21]
i think its my own problem, let me fix my reference image channel first.

**Comment by Matt-JyS** [comment]
Yes. i am sorry to open this issue. Issues were due to my faults.
1. The data_dir in eval.yaml should be the reference folder, not specific font images folder. (should be the upper directory of font images folders.)
2. Reference images should be with single-channel, not RGB images.

Hope thoses lessons can be helpful for those who got same problems like me. Thanks.

**Comment by 8uos** [comment]
Thank you for sharing your tips!
