### ISSUE TITLE
OSError: symbolic link privilege not held

### ISSUE THREAD

**Issue by Chanarin** [clovaai/mxfont#23]
Thanks for your fantastic work.
I got this error when I tried to train the model with my dataset. Here is the setting that I changed:
# etc
save: all-last
print_freq: 100
val_freq: 1000
save_freq: 5000
tb_freq: 100
##############################################################################################
INFO::07/20 00:14:51 | Step    5000
|D             2.925 |G             0.963 |FM            0.086 |R_font        0.710 |F_font        0.760 |R_uni         0.710 |F_uni         0.725
|AC_s          0.110 |AC_c          0.959 |cr_AC_s      -3.527 |cr_AC_c      -2.403 |AC_acc_s      95.8% |AC_acc_c      60.0%
|AC_g_s        0.642 |AC_g_c        1.269 |cr_AC_g_s    -3.527 |cr_AC_g_c    -2.403 |AC_g_acc_s    81.4% |AC_g_acc_c    48.2%
|L1            0.012 |INDP_EXP     0.0266 |INDP_FACT    0.0617
INFO::07/20 00:14:51 | Validation at Epoch = 30.303
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    main()
  File "train.py", line 181, in main
    train(args, cfg)
  File "train.py", line 167, in train
    trainer.train(trn_loader, st_step, cfg.max_iter)
  File "D:\mxfont\trainer\fact_trainer.py", line 198, in train
    self.save(loss_dic['g_total'], self.cfg.save, self.cfg.get('save_freq', self.cfg.val_freq))
  File "D:\mxfont\trainer\base_trainer.py", line 192, in save
    last_ckpt_path.symlink_to(step_ckpt_path)
  File "C:\Users\user\anaconda3\envs\stargan-v2-torch\lib\pathlib.py", line 1352, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held

**Comment by SanghyukChun** [comment]
It seems that your Python does not have a proper privilege. After a quick Google search, I found an answer that may help you. https://github.com/explosion/spaCy/issues/895

As it is not a problem with our code, I closed the issue. Please search the error message first on the web when the error happended out of the main code.
