### ISSUE TITLE
The Role of Factorize and Defactorize

### ISSUE THREAD

**Issue by jingmingtao** [clovaai/mxfont#33]
Hello, I am very interested in your paper. When reading the code, what are the functions of factorize and deformize, and what are the functions of 'last' and 'skip'

**Comment by 8uos** [comment]
"last" is the last output of each encoder.
"skip" is mid-level feature which is used for the skip-connection.
Both features are required for the reconstruction.

**Comment by jingmingtao** [comment]
thanks very much,&nbsp;I got it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Song ***@***.***&gt;; 
发送时间: 2023年11月21日(星期二) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [clovaai/mxfont] The Role of Factorize and Defactorize (Issue #33)





 
"last" is the last output of each encoder.
 "skip" is mid-level feature which is used for the skip-connection.
 Both features are required for the reconstruction.
