### ISSUE TITLE
What are the meanings of style_facts_s style_facts_c, char_facts_s and char_facts_c

### ISSUE THREAD

**Issue by jingmingtao** [clovaai/mxfont#35]
What is the difference between style_facts_s and style_facts_c?
           What is the difference between char_facts_s and char_facts_c?

            style_facts_s = self.gen.factorize(style_feats, 0)  # (B*n_s, n_exp, *feat_shape)
            style_facts_c = self.gen.factorize(style_feats, 1)
            char_facts_s = self.gen.factorize(char_feats, 0)
            char_facts_c = self.gen.factorize(char_feats, 1)

**Comment by SanghyukChun** [comment]
We will not answer our code line by line. I feel your questions are very rude, without trying to understand our paper and code. I will close all the trivial issues that are well explained in our paper and code.

**Comment by jingmingtao** [comment]
No, it's because I'm a beginner. I've read it many times but I can't understand. If you feel rude, I'm sorry

**Comment by jingmingtao** [comment]
If you feel that my question is very rude and my intelligence is not enough, I'm sorry, I won't ask the question anymore. Thank you

**Comment by SanghyukChun** [comment]
In the previous thread, I found that you did try a wrong approach with our method. MX-Font aims to few-shot font generation, where **the model is pre-trained with a number of font libraries first**, and then generate characters with **a few references** without training on the new style.

https://github.com/clovaai/mxfont/blob/main/inference.ipynb
Check this `inference.ipynb` for how to generate (or reconstruct the remaining characters) with only a few reference characters **without training on the new style**.

**Comment by jingmingtao** [comment]
Thank you, I will work harder to study and research
