### ISSUE TITLE
about FID

### ISSUE THREAD

**Issue by ecnuycxie** [clovaai/mxfont#5]
do you measure the style-aware and content-aware FID using all the generated images instead of measuring the FID of each generated style and calculating the average?

**Comment by 8uos** [comment]
Hi, we measured the FID in two different ways.
Firstly, for the CHN → CHN case, we have ground-truth images, thus, we measured the style-aware and content-aware FIDs between all generated images and corresponding ground truth images.
Secondly, for the CHN → KOR case, we don't have GT images (namely, Korean characters in a Chinese font), thus, we measured the FID of each style/character and calculated the average in this case.

Hope this answer can help you.
